palette:
  top: '#c21e3d'
  bottom: '#c21e3d'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#0071b3'
logo: 'public://color/bartik-b10a7ab3/logo.svg'
stylesheets:
  - 'public://color/bartik-b10a7ab3/colors.css'
files:
  - 'public://color/bartik-b10a7ab3/logo.svg'
  - 'public://color/bartik-b10a7ab3/colors.css'
